/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.LED_strip;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/** Subsystem that controls an addressable LED strip using a CANdle. */
public class LEDStripAnimation extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("rio");
  private final CANdle m_candle = new CANdle(10, kCANBus);

  private final ColorFlowAnimation m_slot0Animation =
      new ColorFlowAnimation(0, 7)
          .withSlot(0)
          .withColor(new RGBWColor(255, 179, 26, 0))
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(25));

  private final SolidColor[] m_colors = new SolidColor[] {};

  public LEDStripAnimation() {
    setDefaultCommand(updateLEDs());
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(
        () -> {
          for (var solidColor : m_colors) {
            m_candle.setControl(solidColor);
          }
          m_candle.setControl(m_slot0Animation);
        });
  }
}
